title = "Mouleeshvar G"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Coimbatore, India"
favicon = "/favicon.ico"
firstName = "Mouleeshvar "
lastName = "G"
phone = "+91-9500648586"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "www.linkedin.com/in/mouleeshvar-ganesan"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Mouleesh23/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
